config/routes.rb
Website::Application.routes.draw do

  resources :locations

resources :comments
resources :attractions
resources :welcome

devise_for :admins
devise_for :users , controllers: {users: 'users', sessions: 'sessions'}

  root :to => 'welcome#index'

  get '/about' => 'welcome#about'
  get '/whats' => 'welcome#whats'
  get '/survey' => 'welcome#survey'
  get '/help' => 'welcome#help'
  get '/contact' => 'welcome#contact'
 
  devise_scope :user do

 get '/signup' => 'devise/registrations#new'
 get '/signin' => 'devise/sessions#new'
 post 'users/sign_in' => 'sessions#create'
 get'/users/sign_out' => 'sessions#destroy'
  end

  scope "(:locale)" do
     resources :index
     resources :about
     resources :help
     resources :contact
     resources :whats
     resources :survey

  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	
	belongs_to :user
  	validates :user_id, presence: true
    validates :description, presence: true, length: { maximum: 140 }
  	default_scope -> { order('created_at DESC') }
  	translates :user_id, :title, :description
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user

  # GET /comments
  # GET /comments.json
  def index
   # @comments = Comment.all
    @comments = Comment.where(:user_id => current_user)
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.create(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :title, :description)
    end

 

  def signed_in_user
    unless signed_in?
      redirect_to signin_url, notice: "Please sign in."
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper

end

app/views/comments/_form.html.erb
  <%= form_for(@comment) do |f| %>
    <% if @comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

        <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

app/views/comments/edit.html.erb
<div class = "content_form">
	<h1><%=t('.edit_comment')%></h1>

	<%= render 'form' %>

	<%= link_to t('.show'), @comment %> |
	<%= link_to t('.back'), comments_path %>
</div>

app/views/comments/index.html.erb
<h1><%= t('.list_comments')%></h1>

<table>
  <thead>
    <tr>
      <th><%= t('.title')%></th>
      <th><%= t('.description')%></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.title %></td>
        <td><%= comment.description %></td>
        <td><%= link_to t('.show'), comment %></td>
        <td><%= link_to t('.edit'), edit_comment_path(comment) %></td>
        <td><%= link_to t('.destroy'), comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('.new_comment'), new_comment_path %>

app/views/comments/new.html.erb
<div class = "content_form">
	<h1><%=t('.new_comment')%></h1>

	<%= render 'form' %>

	<%= link_to t('.back'), comments_path %>
</div>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%=t('.title')%>:</strong>
  <%= @comment.title %>
</p>

<p>
  <strong><%= t('.description')%>:</strong>
  <%= @comment.description %>
</p>

<%= link_to t('.edit'), edit_comment_path(@comment) %> 
<%= link_to t('.back'), comments_path %>