config/routes.rb
Website::Application.routes.draw do

  resources :locations

resources :comments
resources :attractions
resources :welcome

devise_for :admins
devise_for :users , controllers: {users: 'users', sessions: 'sessions'}

  root :to => 'welcome#index'

  get '/about' => 'welcome#about'
  get '/whats' => 'welcome#whats'
  get '/survey' => 'welcome#survey'
  get '/help' => 'welcome#help'
  get '/contact' => 'welcome#contact'
 
  devise_scope :user do

 get '/signup' => 'devise/registrations#new'
 get '/signin' => 'devise/sessions#new'
 post 'users/sign_in' => 'sessions#create'
 get'/users/sign_out' => 'sessions#destroy'
  end

  scope "(:locale)" do
     resources :index
     resources :about
     resources :help
     resources :contact
     resources :whats
     resources :survey

  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="large-12 columns">
      <hr>

      <div class="row">
        <div class="large-4 columns">
          <p><small><a href="">Ecuador Travel</a> by Andrea Becerra</small></p>
        </div>
        <div class="large-4 columns">
          <p><%= link_to t('.about'),   about_path %></p>
        </div>

        <div class="large-4 columns">
          <p><%= link_to t('.contact'), contact_path %></p>
        </div>
      </div>
    </div>
  </footer>

app/views/layouts/_header.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to t('.name'), root_path, id: "logo" %></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li><%= link_to_unless I18n.locale == :es, "Español", locale: :es %></li>
      <li><%= link_to_unless I18n.locale == :en, "English", locale: :en %></li>

      <li class="active"><%= link_to  t('.home'), root_url %></li>


     
      <li><%= link_to  t('.help'),    help_path %></li>
      <li><%= link_to  t('.signup'), new_user_registration_path %></li>
         <% if user_signed_in? %>
           <li><%= link_to  t('.locations'), locations_path %></li>
          <li><%= link_to t('.attractions'), attractions_path %></li>
          <li><%= link_to t('.comments'),    comments_path %></li>
           <li class="has-dropdown">
            <a href="#"><%= t('.account') %></a>
             <ul class="dropdown">
            <li><%= link_to  t('.profile'), '#' %></li>
            <li><%= link_to  t('.edit'), edit_user_registration_path %></li>
            <li><%= link_to  t('.signout'), destroy_user_session_path, method: "delete" %></li>
         <% else %>
            <li><%= link_to  t('.signin'), new_user_session_path %></li>
         <% end %>
        </ul>
      </li>
    </ul>
  </section>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Tourism" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render 'layouts/header' %>
    <div class="container">

      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    
    <%= javascript_include_tag "application" %>
  </body>
</html>