config/routes.rb
Website::Application.routes.draw do

  resources :locations

resources :comments
resources :attractions
resources :welcome

devise_for :admins
devise_for :users , controllers: {users: 'users', sessions: 'sessions'}

  root :to => 'welcome#index'

  get '/about' => 'welcome#about'
  get '/whats' => 'welcome#whats'
  get '/survey' => 'welcome#survey'
  get '/help' => 'welcome#help'
  get '/contact' => 'welcome#contact'
 
  devise_scope :user do

 get '/signup' => 'devise/registrations#new'
 get '/signin' => 'devise/sessions#new'
 post 'users/sign_in' => 'sessions#create'
 get'/users/sign_out' => 'sessions#destroy'
  end

  scope "(:locale)" do
     resources :index
     resources :about
     resources :help
     resources :contact
     resources :whats
     resources :survey

  end

end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  before_action :set_attraction, only: [:show, :edit, :update, :destroy]

  # GET /attractions
  # GET /attractions.json
  def index
    @attractions = Attraction.all
  end

  # GET /attractions/1
  # GET /attractions/1.json
  def show
  end

  # GET /attractions/new
  def new
    @attraction = Attraction.new
  end

  # GET /attractions/1/edit
  def edit
  end

  # POST /attractions
  # POST /attractions.json
  def create
    @attraction = Attraction.new(attraction_params)

    respond_to do |format|
      if @attraction.save
        format.html { redirect_to @attraction, notice: 'Attraction was successfully created.' }
        format.json { render action: 'show', status: :created, location: @attraction }
      else
        format.html { render action: 'new' }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attractions/1
  # PATCH/PUT /attractions/1.json
  def update
    respond_to do |format|
      if @attraction.update(attraction_params)
        format.html { redirect_to @attraction, notice: 'Attraction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attractions/1
  # DELETE /attractions/1.json
  def destroy
    @attraction.destroy
    respond_to do |format|
      format.html { redirect_to attractions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attraction
      @attraction = Attraction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attraction_params
      params.require(:attraction).permit(:name, :description, :address, :phone, :website, :openning_hours)
    end
end

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/views/attractions/_form.es.html .erb
  <%= form_for(@attraction) do |f| %>
    <% if @attraction.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@attraction.errors.count, "error") %> prohibited this attraction from being saved:</h2>

        <ul>
        <% @attraction.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_field :description %>
    </div>
    <div class="field">
      <%= f.label :address %><br>
      <%= f.text_field :address %>
    </div>
    <div class="field">
      <%= f.label :phone %><br>
      <%= f.text_field :phone %>
    </div>
    <div class="field">
      <%= f.label :website %><br>
      <%= f.text_field :website %>
    </div>
    <div class="field">
      <%= f.label :openning_hours %><br>
      <%= f.text_field :openning_hours %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

app/views/attractions/_form.html.erb
  <%= form_for(@attraction) do |f| %>
    <% if @attraction.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@attraction.errors.count, "error") %> prohibited this attraction from being saved:</h2>

        <ul>
        <% @attraction.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_field :description %>
    </div>
    <div class="field">
      <%= f.label :address %><br>
      <%= f.text_field :address %>
    </div>
    <div class="field">
      <%= f.label :phone %><br>
      <%= f.text_field :phone %>
    </div>
    <div class="field">
      <%= f.label :website %><br>
      <%= f.text_field :website %>
    </div>
    <div class="field">
      <%= f.label :openning_hours %><br>
      <%= f.text_field :openning_hours %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

app/views/attractions/edit.es.html.erb
<div class = "content_attractions">
	<h1>Editar Atraccion</h1>

	<%= render 'form' %>

	<%= link_to 'Mostar', @attraction %> |
	<%= link_to 'Atras', attractions_path %>
</div>

app/views/attractions/edit.html.erb
<div class = "content_attractions">
	<h1>Editing attraction</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @attraction %> |
	<%= link_to 'Back', attractions_path %>
</div>

app/views/attractions/index.es.html.erb
<h1>Lista de Attracciones</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Direccion</th>
      <th>Telefono</th>
      <th>Pagina Web</th>
      <th>Horario de Atencion</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @attractions.each do |attraction| %>
      <tr>
        <td><%= attraction.name %></td>
        <td><%= attraction.description %></td>
        <td><%= attraction.address %></td>
        <td><%= attraction.phone %></td>
        <td><%= attraction.website %></td>
        <td><%= attraction.openning_hours %></td>
        <td><%= link_to 'Mostrar', attraction %></td>
        <td><%= link_to 'Editar', edit_attraction_path(attraction) %></td>
        <td><%= link_to 'Borrar', attraction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Atraccion', new_attraction_path %>

app/views/attractions/index.html.erb
<h1>Listing attractions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
      <th>Openning hours</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @attractions.each do |attraction| %>
      <tr>
        <td><%= attraction.name %></td>
        <td><%= attraction.description %></td>
        <td><%= attraction.address %></td>
        <td><%= attraction.phone %></td>
        <td><%= attraction.website %></td>
        <td><%= attraction.openning_hours %></td>
        <td><%= link_to 'Show', attraction %></td>
        <td><%= link_to 'Edit', edit_attraction_path(attraction) %></td>
        <td><%= link_to 'Destroy', attraction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attraction', new_attraction_path %>

app/views/attractions/new.es.html.erb
<div class = "content_attractions">
	<h1>Nueva Attraction</h1>

	<%= render 'form' %>

	<%= link_to 'Atras', attractions_path %>
</div>

app/views/attractions/new.html.erb
<div class = "content_attractions">
	<h1>New attraction</h1>

	<%= render 'form' %>

	<%= link_to 'Back', attractions_path %>
</div>

app/views/attractions/show.es.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @attraction.name %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @attraction.description %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @attraction.address %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @attraction.phone %>
</p>

<p>
  <strong>Pagina Web:</strong>
  <%= @attraction.website %>
</p>

<p>
  <strong>Horario de Atencion:</strong>
  <%= @attraction.openning_hours %>
</p>

<%= link_to 'Editar', edit_attraction_path(@attraction) %> |
<%= link_to 'Atras', attractions_path %>

app/views/attractions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @attraction.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @attraction.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @attraction.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @attraction.phone %>
</p>

<p>
  <strong>Website:</strong>
  <%= @attraction.website %>
</p>

<p>
  <strong>Openning hours:</strong>
  <%= @attraction.openning_hours %>
</p>

<%= link_to 'Edit', edit_attraction_path(@attraction) %> |
<%= link_to 'Back', attractions_path %>